name: steganograph
description: Steganograph is a pure Dart steganography library which supports hiding mesages and files in images with an option to encrypt embedded secrets for more security.
homepage: https://github.com/Crazelu/steganograph

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies: 
  image: ^3.2.0
  image_size_getter: ^2.1.1
  crypton: ^2.0.5
  igodo: ^1.0.0
  aes256gcm: ^1.0.1


