name: steganograph
description: A Dart library which supports hiding data in images using LSB steganography.
repository: https://github.com/Crazelu/steganograph
issue_tracker: https://github.com/Crazelu/steganograph/issues
topics: [steganography]

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  image: ^4.2.0
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.5

